name: Deploy

on: 
  push:
    branches: 
      - master

env:
  baseURL: https://swift-project.github.io/homepage

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - run: npm install
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
         hugo-version: 'latest'
         extended: true
      - name: Checkout gh-pages worktree
        run: |
          rm -rf public 
          git worktree add -B gh-pages public origin/gh-pages
          rm -rf public/*
      - name: Build
        run: hugo --minify --baseURL ${{ env.baseURL }}
      - name: Deploy 🚀
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          cd public
          git add --all
          git commit -m "Automatic deployment commit" | true
          cd ..
          git push origin gh-pages | true
