name: Deploy

on: 
  push:
    branches: 
      - homepage

env:
  baseURL: https://swift-project.github.io
  CNAME_URL: swift-project.org

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - run: npm install
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
         hugo-version: 'latest'
         extended: true
      - name: Checkout master worktree
        run: |
          rm -rf public 
          git worktree add -B master public origin/master
          rm -rf public/*
          echo ${{ env.CNAME_URL }} > public/CNAME
      - name: Build
        run: hugo --minify --baseURL ${{ env.baseURL }}
      - name: Create README
        run: echo '# DO NOT COMMIT/PUSH TO MASTER! ONLY FOR GITHUB PAGES!' > public/README.md
      - name: Deploy 🚀
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          cd public
          git add --all
          git commit -m "Automatic deployment commit" | true
          cd ..
          git push origin master | true
